# Generated by Django 4.0.4 on 2022-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['userName'],
            },
        ),
        migrations.CreateModel(
            name='UserTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('tabName', models.CharField(default='Empty Tab', max_length=100)),
                ('tabDesc', models.CharField(default='', max_length=100)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['userName'],
            },
        ),
    ]
